config/routes.rb
Rails.application.routes.draw do
  resources :bici_usuarios
  get '/bici_usuarios', to: 'bici_usuarios#index'
    get '/bici_usuarios/new', to: 'bici_usuarios#new'
  post '/bici_usuarios', to: 'bici_usuarios#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bici_usuario.rb
class BiciUsuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bici_usuarios_controller.rb
class BiciUsuariosController < ApplicationController

def index
	@usu = BiciUsuario.all
end
    def new
        @usu = BiciUsuario.new()
    end
    def create
        @usu = BiciUsuario.new (bici_usuario_params)
        if @usu.save
            redirect_to bici_usuarios_path
        else
            render :new
        end
    end

    def edit
        @usu = BiciUsuario.find(params[:id])
    end
    def show
        @usu = BiciUsuario.find(params[:id])
    end
    def update 
        @usu = BiciUsuario.find(params[:id])
        if @usu.update(product_params)
            redirect_to bici_usuarios_path 
        else    
             render :edit
        end
    end

    def destroy
        @usu = BiciUsuario.find(params[:id])
        @usu.destroy
        redirect_to bici_usuarios_path
    end

    private 
    def bici_usuario_params
    params.require(:bici_usuario).permit(:username,
															:name,
															:document,
															:email,
															:telephone,
															:password,
															:age
															)
end		
   end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bici_usuarios_helper.rb
module BiciUsuariosHelper
end

app/views/bici_usuarios/index.html.erb
<div class="container">
<h3 class="text-center">Listado de Usuarios</h3>

<table class="table table-hover">
   <tr>
    <thead>
    <th>Nombre</th>
    <th>Email</th>
    <th>Documento</th>
	<th>Telefono</th>
	<th>Edad</th>
	<th>Acciones</th>
    </thead>
   </tr>
   <% @usu.each do |usu| %>
   <tr>
      <td><%= usu.name %></td>
      <td><%= usu.email %></td>
      <td><%= usu.document %> </td>
	  <td><%= usu.telephone %> </td>
	  <td><%= usu.age %> </td>
	  <td>
      
      <a class="btn btn-success" href="<%= edit_bici_usuario_path(BiciUsuario) %>"> <i class="fas fa-pencil-alt"></i> Editar</a> 
      <%= link_to "Ver", bici_usuario_path(BiciUsuario)%>
      </td>
   </tr>
   <% end %>
</table>
<br>
<p> Para agregar un nuevo producto haga clic <a class="btn btn-primary" href="/bici_usuarios/new"><span class="fas fa-plus"></span> Aqui</a> </p>
</div>

app/views/bici_usuarios/new.html.erb
<div class="container">
    <h3 class="text-center">Agregar Nuevo Usuario</h3>
<div class="row">
        <%= form_for @usu do |f| %>

    <div class="col-xs-1">
            <%= f.label :username %>
            <%= f.text_field :username %>
        </div>
        <div class="col-xs-1">
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>

        <div class="col-xs-1">
            <%= f.label :document %>
            <%= f.text_field :document %>
        </div>

        <div class="col-xs-1">
            <%= f.label :email %>
            <%= f.text_field :email, type:"email"%>
        </div>


        <div class="col-xs-1">
            <%= f.label :telephone %>
            <%= f.number_field :telephone %>
        </div>
</div>

    <div class="col-xs-1">
            <%= f.label :password %>
            <%= f.text_field :password, type:"password" %>
    </div>
      <div class="col-xs-1">
            <%= f.label :age %>
            <%= f.number_field :age %>
      </div>
        <div>
            <%= f.submit class:"btn btn-success" %>
        </div>
        <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<title>Bici Usuarios</title>

    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>